import { writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import {
	type FeatureMeta,
	type OrquestraConfig,
	type OrquestraSpec,
	initOrquestra,
	resetOrquestraInstance,
} from "@orquestra/core";
import { discoverFeatureFiles } from "../loaders/discovery";
import { configToWorkerOptions } from "../runner/config-mapper";
import { createOrquestraJiti } from "../transform";
import { type ExtractedMacro, extractMacros } from "./macro-extractor";

export interface GenerateTypesOptions {
	config: OrquestraConfig;
	configDir: string;
	spec: OrquestraSpec | null;
	outputDir: string;
	tsconfigPath?: string;
}

export async function generateTypes(options: GenerateTypesOptions): Promise<string> {
	const featureFiles = discoverFeatureFiles({
		testMatch: options.config.testMatch,
		configDir: options.configDir,
	});

	const meta = await collectFeatureMeta(options.config, featureFiles, {
		cwd: options.configDir,
		tsconfigPath: options.tsconfigPath,
	});
	const personas = uniqSorted(meta.map((m) => m.as));
	const domains = uniqSorted([
		...(options.spec?.domains ?? []).map((d) => d.name),
		...meta.map((m) => m.domain).filter((d): d is string => typeof d === "string"),
	]);

	const macros = extractMacros(options.configDir);

	const outputPath = resolve(options.outputDir, "orquestra.d.ts");
	const content = renderDts({ personas, domains, macros, outputPath });

	writeFileSync(outputPath, content);
	return outputPath;
}

interface CollectFeatureMetaContext {
	cwd: string;
	tsconfigPath?: string;
}

async function collectFeatureMeta(
	config: OrquestraConfig,
	featureFiles: string[],
	ctx: CollectFeatureMetaContext,
): Promise<FeatureMeta[]> {
	const jiti = createOrquestraJiti({
		id: import.meta.url,
		cwd: ctx.cwd,
		tsconfigPath: ctx.tsconfigPath,
	});

	resetOrquestraInstance();
	const orq = initOrquestra(configToWorkerOptions(config));
	for (const file of featureFiles) {
		try {
			await jiti.import(file);
		} catch {
			// If a feature file fails to load (missing setup dependency etc),
			// skip it - type generation shouldn't require full runtime.
		}
	}
	return orq.getFeatureMeta();
}

interface RenderOptions {
	personas: string[];
	domains: string[];
	macros: ExtractedMacro[];
	outputPath: string;
}

function renderDts({ personas, domains, macros, outputPath }: RenderOptions): string {
	const outputDir = dirname(outputPath);
	const imports: string[] = [];
	const macroEntries: string[] = [];

	for (const macro of macros) {
		const importPath = toImportPath(relative(outputDir, macro.filePath));
		imports.push(`import type { ${macro.className} } from ${JSON.stringify(importPath)};`);
		macroEntries.push(`\t\t\t${JSON.stringify(macro.title)}: ExtractMacroContext<${macro.className}>;`);
	}

	const personasUnion = personas.length ? personas.map((p) => JSON.stringify(p)).join(" | ") : "never";
	const domainsUnion = domains.length ? domains.map((d) => JSON.stringify(d)).join(" | ") : "never";

	return `// AUTO-GENERATED by @orquestra/runner - do not edit
import type { OrquestraMacro } from "@orquestra/core";
${imports.join("\n")}

type ExtractMacroContext<M> = M extends OrquestraMacro<infer C> ? C : never;

declare module "@orquestra/core" {
	interface OrquestraRegistry {
		personas: ${personasUnion};
		domains: ${domainsUnion};
		macros: {
${macroEntries.join("\n")}
		};
	}
}
`;
}

function toImportPath(relativePath: string): string {
	const normalized = relativePath.replace(/\\/g, "/").replace(/\.ts$/, "");
	return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

function uniqSorted(items: string[]): string[] {
	return Array.from(new Set(items.filter(Boolean))).sort();
}
